Repository AArnott/pr-autocomplete-scratch, pull requests merged in 2020-07, with the labels that each got.

#7 pull request permissions 2
  README.md
Labels: auto-merge

#9 Update README.md
  README.md
Labels: auto-merge

#6 test no permissions
  README.md
Labels: auto-merge

#12 Jessica lim8 test wronglabels
  src/Scratch/Calculator.cs
Labels: auto-merge

#13 Update init.cmd
  init.cmd
Labels: auto-merge, enhancement

#15 Update README.md
  README.md
Labels: auto-squash

#17 Senseless change
  init.ps1
Labels: auto-rebase

#16 FORKED REPO TEST
  README.md
Labels: auto-merge

#18 remove extra punctuation
  README.md
Labels: auto-merge

#20 Update README.md
  README.md
Labels: auto-merge

#21 Delete stale comment in README
  README.md
Labels: auto-squash
